### ISSUE TITLE
Use iPhone’s web push notification system 

### ISSUE THREAD

**Issue by ahanank** [mluggy/teslabox#10] opened 2023-04-11 21:13 UTC
Starting with iOS 16.4.1, Apple devices allows push notifications from web based apps. Anything you ‘add to home screen’ as a bookmark. For instance, a bookmark to tailscale’s name server for TeslaBox can be added to the Home Screen as a bookmark. Using Apple’s implementation, you might not even need telegram/email notifications if the archive link for TeslaBox was able to send a push notification! 
An overview of how it works: 
https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/

Would be awesome to see it implemented. Sorry, android users :/

**Comment by ahanank** [comment] 2023-07-01 18:38
Is this feasible? 

> Starting with iOS 16.4.1, Apple devices allows push notifications from web based apps. Anything you ‘add to home screen’ as a bookmark. For instance, a bookmark to tailscale’s name server for TeslaBox can be added to the Home Screen as a bookmark. Using Apple’s implementation, you might not even need telegram/email notifications if the archive link for TeslaBox was able to send a push notification! An overview of how it works: https://webkit.org/blog/13878/web-push-for-web-apps-on-ios-and-ipados/
> 
> Would be awesome to see it implemented. Sorry, android users :/

Is this feasible?

**Comment by mluggy** [comment] 2023-09-26 20:07
sorry for taking the time. i went through it. very interesting technology. i believe chrome (thus, android) also have this ability. the problem is that you have to go through an actual server/domain which the box doesn't have.

it can, in theory, handled centrally by one of my domains, but it defeats the purpose of privacy and giving the user full control.

for now, i'm closing this, but will have it in mind.

**Closed by mluggy** 2023-09-26 20:07 UTC

**Comment by ahanank** [comment] 2023-09-26 20:12
No worries, thank you for taking the time to consider it. I thought it was quite interesting and would cut the middle man (ie telegram). Understandable though.
